### ISSUE TITLE
Why simple?

### ISSUE THREAD

**Issue by Kikobeats** [feross/simple-concat#2]
It's not a joke; I see [concat-stream](https://github.com/maxogden/concat-stream) implementation and it looks complex, managing encodings and more stuff. 

I want to know what happened to decide create this version 😄 . Maybe you don't need the concat-stream infering encoding implementation in the 99% of cases?

**Comment by feross** [comment]
Yeah, I just wanted something lightweight, with no dependencies, that just waits for a stream to end and gives me a buffer. It's used in WebTorrent.
